In [1]:
import torch

# Gradient Calculation

In [5]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-0.2278,  1.5016,  0.8604], requires_grad=True)


In [7]:
y = x + 3
print(y)

tensor([2.7722, 4.5016, 3.8604], grad_fn=<AddBackward0>)


In [11]:
z = y * y * 2
print(z)

tensor([15.3697, 40.5293, 29.8048], grad_fn=<MulBackward0>)


In [46]:
c = z.mean()
print(c)

tensor(28.5679, grad_fn=<MeanBackward0>)


# Preventing Gradient History

In [49]:
x = torch.randn(3, requires_grad=True)
print(x)


tensor([ 0.4785, -1.4811, -0.8137], requires_grad=True)


In [51]:
x.requires_grad_(False)
print(x)

tensor([ 0.4785, -1.4811, -0.8137])


In [53]:
y = x.detach()
print(y)

tensor([ 0.4785, -1.4811, -0.8137])


In [55]:
with torch.no_grad():
    y = x + 2
    print(y)

tensor([2.4785, 0.5189, 1.1863])


# Dummy Training Example

In [68]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(4):
    model_output = (weights * 3).sum()

    model_output.backward()
    print(weights.grad)

    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
