In [1]:
import torch

# Tensor Basics

In [5]:
x = torch.rand(2, 3)
print(x)
x.dtype

tensor([[0.2096, 0.2294, 0.0552],
        [0.3598, 0.6591, 0.2096]])


torch.float32

In [28]:
# giving specific datatype:
y = torch.rand(2, 3, dtype=torch.float32)
print(y)
y.dtype

tensor([[0.6934, 0.5034, 0.4338],
        [0.5707, 0.2973, 0.0103]])


torch.float32

In [32]:
# addition:
z = x + y
print(z)
z.dtype

tensor([[0.9030, 0.7328, 0.4890],
        [0.9305, 0.9564, 0.2200]])


torch.float32

In [34]:
# we can also use a medthod add for adding x and y:
a = torch.add(x, y)
print(a)

tensor([[0.9030, 0.7328, 0.4890],
        [0.9305, 0.9564, 0.2200]])


In [36]:
# for multiplication:
b = torch.mul(x,y)
print(b)
b.dtype

tensor([[0.1454, 0.1155, 0.0239],
        [0.2053, 0.1959, 0.0022]])


torch.float32

In [40]:
# determine the size:
b.size()

torch.Size([2, 3])

# create from tensor to numpy array:

In [71]:
import numpy as np

In [73]:
a = torch.ones(5)
print(a)
type(a)

tensor([1., 1., 1., 1., 1.])


torch.Tensor

###  Convert Tensor to Numpy

In [75]:
b = a.numpy()
print(b)
type(b)

[1. 1. 1. 1. 1.]


numpy.ndarray

In [77]:
# Modify the tensor:
a.add_(3)
print(a)
type(a)

tensor([4., 4., 4., 4., 4.])


torch.Tensor

In [79]:
# then the numpy array b is automatically changed
print(b)
type(b)

[4. 4. 4. 4. 4.]


numpy.ndarray

### Convert Numpy to Tensor:

In [88]:
a = np.ones(5)
print(a)
type(a)

[1. 1. 1. 1. 1.]


numpy.ndarray

In [98]:
b = torch.from_numpy(a)
print(b)
type(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


torch.Tensor